# Generated by Django 5.2.8 on 2025-12-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('alumno_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AI', max_length=100, null=True)),
                ('email', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AI', max_length=100, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AI', max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AI', max_length=150, null=True)),
                ('tipo_documento', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AI', max_length=20, null=True)),
                ('numero_documento', models.CharField(blank=True, db_collation='Modern_Spanish_CI_AI', max_length=30, null=True, unique=True)),
                ('fecha_registro', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Alumnos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('curso_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_curso', models.CharField(blank=True, max_length=100, null=True)),
                ('nivel', models.CharField(blank=True, max_length=50, null=True)),
                ('duracion_semanas', models.IntegerField(blank=True, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado_curso', models.CharField(blank=True, max_length=20, null=True)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
                ('cupo_ocupado', models.IntegerField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Cursos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inscripciones',
            fields=[
                ('inscripcion_id', models.AutoField(primary_key=True, serialize=False)),
                ('estado_inscripcion', models.CharField(blank=True, max_length=20, null=True)),
                ('total_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_inscripcion', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Inscripciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instructores',
            fields=[
                ('instructor_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(blank=True, max_length=100, null=True)),
                ('especialidad', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'Instructores',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
    ]
